# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: c138a40f8a497ac4fa77f1c3c9928d4fe807d8245686d1c0df43cda8e682dbfd45acd5a8ad5e14bab5bf5e663d255a43c839eb418c98191efa31fe84086a8e17

test:
  domain_name: example.com 
  secret_key_base: cb2748fa333294f1d34f8263d5c5441c77d3d325798c81f13ede83e5633a3e380854e0a31e6ae00dd1bc97cf53cead575d6fdd3ab5bb7c7664ee8abb5431190e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
